---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Action test/validation workflow
name: "Test GitHub Action 🧪"

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions: {}

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  ### Test the GitHub Action in this Repository ###
  tests:
    name: "Test local GitHub Action"
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      # Perform setup prior to running test(s)
      - name: "Checkout sample project repository"
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          repository: "lfreleng-actions/test-python-project"
          path: "test-python-project"

      # Build sample Python project
      - name: "Build Python Project"
        id: build
        # yamllint disable-line rule:line-length
        uses: lfreleng-actions/python-build-action@7ff456c72f1dd50ef212ea7222efc12693221af3 # v1.0.4
        with:
          path_prefix: "test-python-project/"
          tox_build: false

      # Perform Python project tests
      - name: "Run action: ${{ github.repository }}"
        uses: ./
        with:
          # yamllint disable-line rule:line-length
          python_version: "${{ steps.build.outputs.build_python_version }}"
          path_prefix: "test-python-project/"
